#!/bin/bash
# System Health Check - JSON Generator
# Extracted from tasks.sh

set -euo pipefail

# Ensure dependencies are loaded (only if running standalone)
if [[ -z "${MOLE_FILE_OPS_LOADED:-}" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
    source "$SCRIPT_DIR/lib/core/file_ops.sh"
fi

# Get memory info in GB
get_memory_info() {
    local total_bytes used_gb total_gb

    # Total memory
    total_bytes=$(sysctl -n hw.memsize 2> /dev/null || echo "0")
    total_gb=$(LC_ALL=C awk "BEGIN {printf \"%.2f\", $total_bytes / (1024*1024*1024)}" 2> /dev/null || echo "0")
    [[ -z "$total_gb" || "$total_gb" == "" ]] && total_gb="0"

    # Used memory from vm_stat
    local vm_output active wired compressed page_size
    vm_output=$(vm_stat 2> /dev/null || echo "")
    page_size=4096

    active=$(echo "$vm_output" | LC_ALL=C awk '/Pages active:/ {print $NF}' | tr -d '.\n' 2> /dev/null)
    wired=$(echo "$vm_output" | LC_ALL=C awk '/Pages wired down:/ {print $NF}' | tr -d '.\n' 2> /dev/null)
    compressed=$(echo "$vm_output" | LC_ALL=C awk '/Pages occupied by compressor:/ {print $NF}' | tr -d '.\n' 2> /dev/null)

    active=${active:-0}
    wired=${wired:-0}
    compressed=${compressed:-0}

    local used_bytes=$(((active + wired + compressed) * page_size))
    used_gb=$(LC_ALL=C awk "BEGIN {printf \"%.2f\", $used_bytes / (1024*1024*1024)}" 2> /dev/null || echo "0")
    [[ -z "$used_gb" || "$used_gb" == "" ]] && used_gb="0"

    echo "$used_gb $total_gb"
}

# Get disk info
get_disk_info() {
    local home="${HOME:-/}"
    local df_output total_gb used_gb used_percent

    df_output=$(command df -k "$home" 2> /dev/null | tail -1)

    local total_kb used_kb
    total_kb=$(echo "$df_output" | LC_ALL=C awk 'NR==1{print $2}' 2> /dev/null)
    used_kb=$(echo "$df_output" | LC_ALL=C awk 'NR==1{print $3}' 2> /dev/null)

    total_kb=${total_kb:-0}
    used_kb=${used_kb:-0}
    [[ "$total_kb" == "0" ]] && total_kb=1 # Avoid division by zero

    total_gb=$(LC_ALL=C awk "BEGIN {printf \"%.2f\", $total_kb / (1024*1024)}" 2> /dev/null || echo "0")
    used_gb=$(LC_ALL=C awk "BEGIN {printf \"%.2f\", $used_kb / (1024*1024)}" 2> /dev/null || echo "0")
    used_percent=$(LC_ALL=C awk "BEGIN {printf \"%.1f\", ($used_kb / $total_kb) * 100}" 2> /dev/null || echo "0")

    [[ -z "$total_gb" || "$total_gb" == "" ]] && total_gb="0"
    [[ -z "$used_gb" || "$used_gb" == "" ]] && used_gb="0"
    [[ -z "$used_percent" || "$used_percent" == "" ]] && used_percent="0"

    echo "$used_gb $total_gb $used_percent"
}

# Get uptime in days
get_uptime_days() {
    local boot_output boot_time uptime_days

    boot_output=$(sysctl -n kern.boottime 2> /dev/null || echo "")
    boot_time=$(echo "$boot_output" | awk -F 'sec = |, usec' '{print $2}' 2> /dev/null || echo "")

    if [[ -n "$boot_time" && "$boot_time" =~ ^[0-9]+$ ]]; then
        local now
        now=$(get_epoch_seconds)
        local uptime_sec=$((now - boot_time))
        uptime_days=$(LC_ALL=C awk "BEGIN {printf \"%.1f\", $uptime_sec / 86400}" 2> /dev/null || echo "0")
    else
        uptime_days="0"
    fi

    [[ -z "$uptime_days" || "$uptime_days" == "" ]] && uptime_days="0"
    echo "$uptime_days"
}

# JSON escape helper
json_escape() {
    # Escape backslash, double quote, tab, and newline
    local escaped
    escaped=$(echo -n "$1" | sed 's/\\/\\\\/g; s/"/\\"/g; s/	/\\t/g' | tr '\n' ' ')
    echo -n "${escaped% }"
}

# Generate JSON output
generate_health_json() {
    # System info
    read -r mem_used mem_total <<< "$(get_memory_info)"
    read -r disk_used disk_total disk_percent <<< "$(get_disk_info)"
    local uptime=$(get_uptime_days)

    # Ensure all values are valid numbers (fallback to 0)
    mem_used=${mem_used:-0}
    mem_total=${mem_total:-0}
    disk_used=${disk_used:-0}
    disk_total=${disk_total:-0}
    disk_percent=${disk_percent:-0}
    uptime=${uptime:-0}

    # Start JSON
    cat << EOF
{
  "memory_used_gb": $mem_used,
  "memory_total_gb": $mem_total,
  "disk_used_gb": $disk_used,
  "disk_total_gb": $disk_total,
  "disk_used_percent": $disk_percent,
  "uptime_days": $uptime,
  "optimizations": [
EOF

    # Collect all optimization items
    local -a items=()

    # Core optimizations (safe and valuable)
    items+=('system_maintenance|DNS 与 Spotlight 检查|刷新 DNS 缓存并验证 Spotlight 状态|true')
    items+=('cache_refresh|Finder 缓存刷新|刷新 QuickLook 缩略图和图标服务缓存|true')
    items+=('saved_state_cleanup|应用状态清理|移除旧的已保存应用状态（30天以上）|true')
    items+=('fix_broken_configs|损坏配置修复|修复损坏的偏好设置文件|true')
    items+=('network_optimization|网络缓存刷新|优化 DNS 缓存并重启 mDNSResponder|true')

    # Advanced optimizations (auto-run, non-destructive or regenerated by macOS)
    items+=('sqlite_vacuum|数据库优化|压缩 Mail、Safari 和 Messages 的 SQLite 数据库（应用运行中则跳过）|true')
    items+=('launch_services_rebuild|LaunchServices 修复|修复"打开方式"菜单和文件关联|true')
    items+=('font_cache_rebuild|字体缓存重建|重建字体数据库以修复渲染问题（浏览器运行中则跳过）|true')
    items+=('dock_refresh|Dock 刷新|修复 Dock 中损坏的图标和视觉问题|true')
    items+=('prevent_network_dsstore|防止 Finder .DS_Store|设置持久化的 Finder 偏好，停止在 SMB/AFP/NFS 和 USB 卷上写入 .DS_Store|true')

    # System performance optimizations (auto-run, non-destructive)
    items+=('memory_pressure_relief|内存优化|释放非活跃内存以提升系统响应速度|true')
    items+=('network_stack_optimize|网络堆栈刷新|刷新路由表和 ARP 缓存以解决网络问题|true')
    items+=('disk_permissions_repair|权限修复|修复用户目录权限问题|true')
    items+=('bluetooth_reset|蓝牙刷新|重启蓝牙模块以修复连接问题（使用中则跳过）|true')
    items+=('spotlight_index_optimize|Spotlight 优化|若搜索缓慢则重建索引（智能检测）|true')
    items+=('periodic_maintenance|定期维护|运行 macOS 每日/每周/每月维护脚本（如果过期）|true')
    items+=('shared_file_list_repair|共享文件列表|修复损坏的 Finder 收藏和最近文档|true')
    items+=('disk_verify|磁盘健康|验证文件系统完整性|true')
    items+=('login_items_audit|登录项|审计登录项中的损坏条目|true')

    # System database cleanup (auto-run, low risk)
    items+=('quarantine_cleanup|隔离数据库清理|清除 Gatekeeper 下载跟踪记录|true')
    items+=('launch_agents_cleanup|启动代理清理|移除二进制文件已不存在的损坏启动代理|true')
    items+=('notification_cleanup|通知|清理旧通知以减少数据库膨胀|true')
    items+=('coreduet_cleanup|使用数据|清理旧的使用跟踪数据|true')

    # Removed high-risk optimizations:
    # - startup_items_cleanup: Risk of deleting legitimate app helpers
    # - system_services_refresh: Risk of data loss when killing system services
    # - dyld_cache_update: Low benefit, time-consuming, auto-managed by macOS

    # Output items as JSON
    local first=true
    for item in "${items[@]}"; do
        IFS='|' read -r action name desc safe <<< "$item"

        # Escape strings
        action=$(json_escape "$action")
        name=$(json_escape "$name")
        desc=$(json_escape "$desc")

        [[ "$first" == "true" ]] && first=false || echo ","

        cat << EOF
    {
      "category": "system",
      "name": "$name",
      "description": "$desc",
      "action": "$action",
      "safe": $safe
    }
EOF
    done

    # Close JSON
    cat << 'EOF'
  ]
}
EOF
}

# Main execution (for testing)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    generate_health_json
fi
