#!/bin/bash

show_clean_help() {
    echo "用法: mo clean [选项]"
    echo ""
    echo "通过移除缓存、日志、临时文件以及已卸载应用的残留来释放磁盘空间。"
    echo ""
    echo "选项:"
    echo "  --dry-run, -n     预览清理操作，不实际执行更改"
    echo "  --external PATH   清理已挂载外部卷上的操作系统元数据"
    echo "  --whitelist       管理受保护路径"
    echo "  --debug           显示详细的操作日志"
    echo "  -h, --help        显示此帮助信息"
}

show_installer_help() {
    echo "用法: mo installer [选项]"
    echo ""
    echo "查找并移除安装程序文件 (.dmg, .pkg, .iso, .xip, .zip)。"
    echo ""
    echo "选项:"
    echo "  --dry-run         预览安装程序清理操作，不实际执行更改"
    echo "  --debug           显示详细的操作日志"
    echo "  -h, --help        显示此帮助信息"
}

show_optimize_help() {
    echo "用法: mo optimize [选项]"
    echo ""
    echo "检查并维护系统健康，应用优化措施。"
    echo ""
    echo "选项:"
    echo "  --dry-run         预览优化操作，不实际执行更改"
    echo "  --whitelist       管理受保护项目"
    echo "  --debug           显示详细的操作日志"
    echo "  -h, --help        显示此帮助信息"
}

show_check_help() {
    echo "用法: mo check [选项]"
    echo ""
    echo "并行运行系统诊断并报告以下状态："
    echo "  - Mole 和 Homebrew 更新"
    echo "  - 系统健康（磁盘、内存、交换空间、运行时间）"
    echo "  - 安全状态（FileVault、防火墙、SIP、Touch ID）"
    echo "  - 配置（白名单、登录项、启动代理）"
    echo "  - 开发者环境（Shell、Git、常用工具链）"
    echo ""
    echo "报告后，可能会提示你应用安全的自动修复"
    echo "（例如清理崩溃报告）或运行可用更新。这两个"
    echo "提示默认选择"否"，因此除非你明确确认，"
    echo "check 命令不会造成破坏。"
    echo ""
    echo "别名:"
    echo "  mo doctor         等同于 mo check"
    echo ""
    echo "选项:"
    echo "  -h, --help        显示此帮助信息"
}

show_touchid_help() {
    echo "用法: mo touchid [命令]"
    echo ""
    echo "配置 Touch ID 用于 sudo 认证。"
    echo ""
    echo "命令:"
    echo "  enable            启用 Touch ID 用于 sudo"
    echo "  disable           禁用 Touch ID 用于 sudo"
    echo "  status            显示当前 Touch ID 状态"
    echo ""
    echo "选项:"
    echo "  --dry-run         预览 Touch ID 更改，不修改 sudo 配置"
    echo "  -h, --help        显示此帮助信息"
    echo ""
    echo "如果未提供命令，将显示交互式菜单。"
}

show_uninstall_help() {
    echo "用法: mo uninstall [选项] [应用名称 ...]"
    echo ""
    echo "以交互方式移除应用程序及其残留文件。"
    echo "可选择直接指定一个或多个应用名称进行卸载。"
    echo "对于已卸载应用的残留，请使用 mo clean。"
    echo ""
    echo "示例:"
    echo "  mo uninstall                   打开交互式应用选择器"
    echo "  mo uninstall slack             卸载 Slack"
    echo "  mo uninstall slack zoom        卸载 Slack 和 Zoom"
    echo "  mo uninstall --dry-run slack   预览 Slack 卸载操作"
    echo "  mo uninstall --list            显示已安装应用及 mo uninstall 接受的名称"
    echo ""
    echo "选项:"
    echo "  --list            列出已安装应用及 mo uninstall 接受的确切名称"
    echo "  --dry-run         预览应用卸载操作，不实际执行更改"
    echo "  --permanent       绕过 macOS 废纸篓，直接 rm -rf 立即删除"
    echo "  --whitelist       卸载不支持白名单（请使用 clean/optimize）"
    echo "  --debug           显示详细的操作日志"
    echo "  -h, --help        显示此帮助信息"
    echo ""
    echo "默认情况下，卸载的文件会移入 macOS 废纸篓，以便"
    echo "恢复。使用 --permanent 可跳过废纸篓步骤。"
}
